<a href="https://colab.research.google.com/github/suhashj/Machine-Learning-projects/blob/main/Uni_stud_monthly_expense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import os
import seaborn as sns
import matplotlib as plt
%matplotlib inline

In [ ]:
data = pd.read_csv("/content/University Students Monthly Expenses.csv")

In [ ]:
data.head()

Gender  Age  Study_year  Living Scholarship Part_time_job Transporting  \
0  Female    21         2.0    Home          No            No           No   
1    Male    25         3.0  Hostel          No           Yes   Motorcycle   
2    Male    23         2.0    Home         Yes            No           No   
3    Male    19         3.0  Hostel          No            No   Motorcycle   
4  Female    19         2.0    Home          No            No   Motorcycle   

  Smoking Drinks Games_&_Hobbies Cosmetics_&_Self-care Monthly_Subscription  \
0      No     No              No                   Yes                   No   
1      No     No             Yes                   Yes                  Yes   
2      No     No              No                    No                  NaN   
3      No     No             Yes                   Yes                  Yes   
4      No     No              No                   Yes                   No   

   Monthly_expenses_$  
0               150.0  
1               220.0  
2               180.0  
3               200.0  
4               300.0

In [ ]:
data.describe(include="all")

Gender         Age  Study_year Living Scholarship Part_time_job  \
count       105  105.000000  101.000000    103         105           100   
unique        2         NaN         NaN      2           2             2   
top     Female          NaN         NaN   Home          No            No   
freq         53         NaN         NaN     67          78            69   
mean        NaN   20.171429    2.653465    NaN         NaN           NaN   
std         NaN    1.898669    1.004347    NaN         NaN           NaN   
min         NaN   17.000000    1.000000    NaN         NaN           NaN   
25%         NaN   19.000000    2.000000    NaN         NaN           NaN   
50%         NaN   19.000000    2.000000    NaN         NaN           NaN   
75%         NaN   22.000000    4.000000    NaN         NaN           NaN   
max         NaN   25.000000    4.000000    NaN         NaN           NaN   

       Transporting Smoking Drinks Games_&_Hobbies Cosmetics_&_Self-care  \
count            91      94     92             105                    92   
unique            3       2      2               2                     2   
top             Car      No     No             Yes                   Yes   
freq             35      72     84              71                    51   
mean            NaN     NaN    NaN             NaN                   NaN   
std             NaN     NaN    NaN             NaN                   NaN   
min             NaN     NaN    NaN             NaN                   NaN   
25%             NaN     NaN    NaN             NaN                   NaN   
50%             NaN     NaN    NaN             NaN                   NaN   
75%             NaN     NaN    NaN             NaN                   NaN   
max             NaN     NaN    NaN             NaN                   NaN   

       Monthly_Subscription  Monthly_expenses_$  
count                    96           99.000000  
unique                    2                 NaN  
top                      No                 NaN  
freq                     50                 NaN  
mean                    NaN          214.949495  
std                     NaN           60.699557  
min                     NaN          140.000000  
25%                     NaN          155.000000  
50%                     NaN          200.000000  
75%                     NaN          250.000000  
max                     NaN          350.000000

In [ ]:
data.isna().sum()

Gender                    0
Age                       0
Study_year                4
Living                    2
Scholarship               0
Part_time_job             5
Transporting             14
Smoking                  11
Drinks                   13
Games_&_Hobbies           0
Cosmetics_&_Self-care    13
Monthly_Subscription      9
Monthly_expenses_$        6
dtype: int64

In [ ]:
data["Study_year"].unique()

array([ 2.,  3.,  1.,  4., nan])

In [ ]:
data["Study_year"]=data["Study_year"].fillna(data["Study_year"].mode()[0])

In [ ]:
data["Living"].unique()

array(['Home', 'Hostel', nan], dtype=object)

In [ ]:
data["Living"]=data["Living"].fillna(data["Living"].mode()[0])

In [ ]:
data["Part_time_job"].unique()

array(['No', 'Yes', nan], dtype=object)

In [ ]:
data["Part_time_job"]=data["Part_time_job"].fillna(data["Part_time_job"].mode()[0])

In [ ]:
data["Transporting"].unique()

array(['No', 'Motorcycle', 'Car', nan], dtype=object)

In [ ]:
data["Transporting"]=data["Transporting"].fillna(data["Transporting"].mode()[0])

In [ ]:
data["Smoking"]=data["Smoking"].fillna(data["Smoking"].mode()[0])

In [ ]:
data["Drinks"]=data["Drinks"].fillna(data["Drinks"].mode()[0])

In [ ]:
data["Cosmetics_&_Self-care"]=data["Cosmetics_&_Self-care"].fillna(data["Cosmetics_&_Self-care"].mode()[0])

In [ ]:
data["Monthly_Subscription"]=data["Monthly_Subscription"].fillna(data["Monthly_Subscription"].mode()[0])

In [ ]:
data["Monthly_expenses_$"]=data["Monthly_expenses_$"].fillna(data["Monthly_expenses_$"].median())

In [ ]:
data.isna().sum()

Gender                   0
Age                      0
Study_year               0
Living                   0
Scholarship              0
Part_time_job            0
Transporting             0
Smoking                  0
Drinks                   0
Games_&_Hobbies          0
Cosmetics_&_Self-care    0
Monthly_Subscription     0
Monthly_expenses_$       0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Gender                 105 non-null    object 
 1   Age                    105 non-null    int64  
 2   Study_year             105 non-null    float64
 3   Living                 105 non-null    object 
 4   Scholarship            105 non-null    object 
 5   Part_time_job          105 non-null    object 
 6   Transporting           105 non-null    object 
 7   Smoking                105 non-null    object 
 8   Drinks                 105 non-null    object 
 9   Games_&_Hobbies        105 non-null    object 
 10  Cosmetics_&_Self-care  105 non-null    object 
 11  Monthly_Subscription   105 non-null    object 
 12  Monthly_expenses_$     105 non-null    float64
dtypes: float64(2), int64(1), object(10)
memory usage: 10.8+ KB


In [ ]:
data.head(1)

Gender  Age  Study_year Living Scholarship Part_time_job Transporting  \
0  Female    21         2.0   Home          No            No           No   

  Smoking Drinks Games_&_Hobbies Cosmetics_&_Self-care Monthly_Subscription  \
0      No     No              No                   Yes                   No   

   Monthly_expenses_$  
0               150.0

In [ ]:
from sklearn import preprocessing
label_encoding = preprocessing.LabelEncoder()

In [ ]:
data['Monthly_Subscription'] = label_encoding.fit_transform(data['Monthly_Subscription'])
data['Monthly_Subscription'].unique()

array([0, 1])

In [ ]:
data['Cosmetics_&_Self-care'] = label_encoding.fit_transform(data['Cosmetics_&_Self-care'])
data['Cosmetics_&_Self-care'].unique()

array([1, 0])

In [ ]:
data['Games_&_Hobbies'] = label_encoding.fit_transform(data['Games_&_Hobbies'])
data['Games_&_Hobbies'].unique()

array([0, 1])

In [ ]:
data['Drinks'] = label_encoding.fit_transform(data['Drinks'])
data['Drinks'].unique()

array([0, 1])

In [ ]:
data['Gender'] = label_encoding.fit_transform(data['Gender'])
data['Gender'].unique()

array([0, 1])

In [ ]:
data['Living'] = label_encoding.fit_transform(data['Living'])
data['Living'].unique()

array([0, 1])

In [ ]:
data['Smoking'] = label_encoding.fit_transform(data['Smoking'])
data['Smoking'].unique()

array([0, 1])

In [ ]:
data['Scholarship'] = label_encoding.fit_transform(data['Scholarship'])
data['Scholarship'].unique()

array([0, 1])

In [ ]:
data['Part_time_job'] = label_encoding.fit_transform(data['Part_time_job'])
data['Part_time_job'].unique()

array([0, 1])

In [ ]:
data = data.join(pd.get_dummies(data['Transporting'], drop_first=True))

In [ ]:
data = data.drop('Transporting', axis=1)

In [ ]:
data.head()

Gender  Age  Study_year  Living  Scholarship  Part_time_job  Smoking  \
0       0   21         2.0       0            0              0        0   
1       1   25         3.0       1            0              1        0   
2       1   23         2.0       0            1              0        0   
3       1   19         3.0       1            0              0        0   
4       0   19         2.0       0            0              0        0   

   Drinks  Games_&_Hobbies  Cosmetics_&_Self-care  Monthly_Subscription  \
0       0                0                      1                     0   
1       0                1                      1                     1   
2       0                0                      0                     0   
3       0                1                      1                     1   
4       0                0                      1                     0   

   Monthly_expenses_$  Motorcycle  No  
0               150.0           0   1  
1               220.0           1   0  
2               180.0           0   1  
3               200.0           1   0  
4               300.0           1   0

In [ ]:
data.dtypes

Gender                     int64
Age                        int64
Study_year               float64
Living                     int64
Scholarship                int64
Part_time_job              int64
Smoking                    int64
Drinks                     int64
Games_&_Hobbies            int64
Cosmetics_&_Self-care      int64
Monthly_Subscription       int64
Monthly_expenses_$       float64
Motorcycle                 uint8
No                         uint8
dtype: object

In [ ]:
data.shape

(105, 14)

In [ ]:
X = data.iloc[:80,:]
y = data.iloc[80:,:]

In [ ]:
X

Gender  Age  Study_year  Living  Scholarship  Part_time_job  Smoking  \
0        0   21         2.0       0            0              0        0   
1        1   25         3.0       1            0              1        0   
2        1   23         2.0       0            1              0        0   
3        1   19         3.0       1            0              0        0   
4        0   19         2.0       0            0              0        0   
..     ...  ...         ...     ...          ...            ...      ...   
75       0   23         4.0       0            0              0        0   
76       0   19         3.0       0            0              0        0   
77       1   23         2.0       0            1              0        0   
78       1   19         3.0       1            0              0        0   
79       0   19         2.0       0            0              0        0   

    Drinks  Games_&_Hobbies  Cosmetics_&_Self-care  Monthly_Subscription  \
0        0                0                      1                     0   
1        0                1                      1                     1   
2        0                0                      0                     0   
3        0                1                      1                     1   
4        0                0                      1                     0   
..     ...              ...                    ...                   ...   
75       0                1                      1                     1   
76       0                1                      1                     1   
77       0                0                      0                     0   
78       0                1                      1                     1   
79       0                0                      1                     0   

    Monthly_expenses_$  Motorcycle  No  
0                150.0           0   1  
1                220.0           1   0  
2                180.0           0   1  
3                200.0           1   0  
4                300.0           1   0  
..                 ...         ...  ..  
75               150.0           0   1  
76               200.0           1   0  
77               180.0           0   1  
78               200.0           1   0  
79               300.0           1   0  

[80 rows x 14 columns]

In [ ]:
y

Gender  Age  Study_year  Living  Scholarship  Part_time_job  Smoking  \
80        1   22         3.0       1            0              1        0   
81        0   21         2.0       0            1              0        0   
82        1   22         3.0       1            0              1        1   
83        0   18         1.0       0            1              0        0   
84        1   19         1.0       0            0              0        0   
85        1   22         3.0       0            0              0        0   
86        1   18         2.0       1            0              0        0   
87        0   18         2.0       0            0              0        0   
88        1   19         2.0       0            0              1        1   
89        0   22         4.0       1            1              1        0   
90        1   18         2.0       1            0              0        0   
91        0   18         2.0       0            0              0        0   
92        1   19         2.0       0            0              1        1   
93        0   22         4.0       1            1              1        0   
94        1   22         4.0       0            0              0        0   
95        0   17         1.0       0            0              0        0   
96        0   19         2.0       1            0              0        0   
97        0   23         4.0       0            0              0        0   
98        0   19         3.0       0            0              0        0   
99        1   23         2.0       0            1              0        0   
100       1   19         3.0       1            0              0        0   
101       0   19         2.0       0            0              0        0   
102       1   22         3.0       1            0              1        0   
103       0   21         2.0       0            1              0        0   
104       1   22         3.0       1            0              1        1   

     Drinks  Games_&_Hobbies  Cosmetics_&_Self-care  Monthly_Subscription  \
80        1                1                      0                     0   
81        0                1                      0                     1   
82        0                1                      1                     1   
83        0                0                      1                     1   
84        0                1                      1                     0   
85        0                0                      1                     1   
86        0                1                      0                     0   
87        0                1                      1                     0   
88        0                1                      1                     0   
89        0                0                      1                     1   
90        0                1                      0                     0   
91        0                1                      1                     0   
92        0                1                      1                     0   
93        0                0                      1                     1   
94        0                1                      0                     0   
95        0                0                      0                     0   
96        0                1                      1                     0   
97        0                1                      1                     1   
98        0                1                      1                     1   
99        0                0                      0                     0   
100       0                1                      1                     1   
101       0                0                      1                     0   
102       1                1                      0                     0   
103       0                1                      0                     1   
104       0                1                      1                     1   


In [ ]:
#train
X1 = X.drop("Monthly_expenses_$", axis=1)

In [ ]:
y1 = X["Monthly_expenses_$"]

In [ ]:
#test
X2 = y.drop("Monthly_expenses_$", axis=1)
y2 = y["Monthly_expenses_$"]

In [ ]:
X1.head(1)

Gender  Age  Study_year  Living  Scholarship  Part_time_job  Smoking  \
0       0   21         2.0       0            0              0        0   

   Drinks  Games_&_Hobbies  Cosmetics_&_Self-care  Monthly_Subscription  \
0       0                0                      1                     0   

   Motorcycle  No  
0           0   1

In [ ]:
y1.head()

0    150.0
1    220.0
2    180.0
3    200.0
4    300.0
Name: Monthly_expenses_$, dtype: float64

In [ ]:
X2.head(1)

Gender  Age  Study_year  Living  Scholarship  Part_time_job  Smoking  \
80       1   22         3.0       1            0              1        0   

    Drinks  Games_&_Hobbies  Cosmetics_&_Self-care  Monthly_Subscription  \
80       1                1                      0                     0   

    Motorcycle  No  
80           0   0

In [ ]:
y2.head()

80    150.0
81    200.0
82    200.0
83    150.0
84    200.0
Name: Monthly_expenses_$, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, y_train, x_test, y_test = train_test_split(X1,y1,random_state=42, test_size=0.3)

In [ ]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

rf1 = RandomForestClassifier(max_depth=8,class_weight='balanced')
rf1.fit(X1, y1)

RandomForestClassifier(class_weight='balanced', max_depth=8)

In [ ]:
y1_pred = rf1.predict(X1)
y2_pred = rf1.predict(X2)

In [ ]:
print("Accuracy on training set: {:.3f}".format(rf1.score(X1, y1)))
print("Accuracy on testing set: {:.3f}".format(rf1.score(X2, y2)))

Accuracy on training set: 0.950
Accuracy on testing set: 0.880


In [ ]:
y2.to_csv("Output", index=False)